### ISSUE TITLE
"Test Connection" doesn't work

### ISSUE THREAD

**Issue by Ramnarayan-Kotagiri** [tuyennn/AutoInstagramPost#14]
"Test Connection" says " _Unauthorized Instagram Account, check your user/password settings_ " when keyed in the Intagram Credentials.

**Comment by tuyennn** [comment]
@Ramnarayan-Kotagiri This due by the API was appeared as an android application emulation. should keep it VERY frequent (definitely NEVER longer than 6 hours for 1 login). so that Instagram sees you as a real client that keeps quitting and opening their app like a REAL user. Otherwise they WILL detect you as a bot and silently BLOCK features.

This feature might cause risk, I will take a look to have a workaround

**Comment by tuyennn** [comment]
@Ramnarayan-Kotagiri Your issue was fixed on master branch
